###############################################################################
# Copyright (C) 2020-2021 Habana Labs, Ltd. an Intel Company
# All Rights Reserved.
#
# Unauthorized copying of this file or any element(s) within it, via any medium
# is strictly prohibited.
# This file contains Habana Labs, Ltd. proprietary and confidential information
# and is subject to the confidentiality and license agreements under which it
# was provided.
###############################################################################
model: "vgg_segnet"
env_variables:
  LOG_LEVEL_ALL: 6

parameters:
  checkpoints_path: "vgg_segnet_fp32/"
  train_images: "dataset1/images_prepped_train/"
  train_annotations: "dataset1/annotations_prepped_train/"
  val_images: "dataset1/images_prepped_test/"
  val_annotations: "dataset1/annotations_prepped_test/"
  n_classes: 12
  input_height: 320
  input_width: 640
  model_name: "vgg_segnet"
  model_dir: "/tmp/vgg_segnet"
  epoch: 125
  batch_size: 16
